//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task123
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> purpose_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<int> status_id { get; set; }
        public string annotation { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual status123 status123 { get; set; }
    }
}
